# -*- coding: utf-8 -*-
"""DWH Lab Assignment 04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H0tVYg8c4W_lekSa7CvmrYfMPLG5J-qm
"""

!pip install apyori

import matplotlib.pyplot as plt
from apyori import apriori
import pandas as pd

def load_mushrooms():
    return pd.read_csv('mushrooms.csv')

# Load the built-in dataset
dataset = load_mushrooms()

transactions = []
for item in dataset:
    transactions.append(item)

# Run the Apriori algorithm
results = list(apriori(transactions, min_support=0.1, min_confidence=0.5))

# Print the results
for item in results:
    # Get the items and support for the itemset
    items = item[0]
    support = item[1]

    # Get the rules and confidence for the itemset
    for rule in item[2]:
        antecedent = rule[0]
        consequent = rule[1]
        confidence = rule[2]

        # Print the rule
        print(f"{antecedent} -> {consequent} (Confidence: {confidence:.3f}, Support: {support:.3f})")

# Extract the rules and supports for each itemset
rules = [list(x[2]) for x in results]
supports = [x[1] for x in results]

# Flatten the rules and supports lists
rules = [item for sublist in rules for item in sublist]
supports = [item for sublist in supports for item in sublist]

# Extract the antecedents and consequents for each rule
antecedents = [list(x[0]) for x in rules]
consequents = [list(x[1]) for x in rules]
confidences = [x[2] for x in rules]

# Visualize the results with a bar chart
plt.bar(range(len(supports)), supports, color='b', alpha=0.5, label='Support')
plt.xticks(range(len(supports)), antecedents, rotation=45)
plt.xlabel('Antecedent')
plt.ylabel('Support')
plt.title('Support for Each Antecedent')
plt.legend()
plt.show()